name: roxygen-check

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  roxygen-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true  # faster, reproducible binaries on Ubuntu

      # NEW: install devtools + roxygen2 using r-lib/actions
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # 'any::' installs from CRAN; 'local::.' also installs your package deps
          extra-packages: >
            any::devtools,
            any::roxygen2
          needs: roxygen

      - name: Run devtools::document()
        run: |
          Rscript -e 'devtools::document(quiet = TRUE)'

      - name: Fail if docs changed
        run: |
          git status --porcelain
          git diff --name-only --exit-code || (echo 'Roxygen docs are not up-to-date. Run devtools::document() locally and commit man/ + NAMESPACE.' && exit 1)